---
- name: Setup Vprofile bastion host
  hosts: localhost
  #connection: local 
  gather_facts: False
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/vpc-setup.txt

    - name: Import VPC setup Variable - vpc_output_vars
      include_vars: vars/vpc_output_vars
    - name: create a new vprofile EC2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
    - debug:
        var: key_out

    - name: Save private key to bastion key file
      copy:
        content: "{{key_out.key.private_key}}"
        dest: ./bastion-key.pem
        mode: 0600
      when: key_out.changed

    - name: Create Sec Grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out

    # - name: Insert/update "BastionSGid" 
    #   blockinfile:
    #     path: vars/vpc_output_vars
    #     backup: yes
    #     block:
    #       BastionSGid: "{{BastionSG_out.group_id}}"
    - name: Insert/Update "BastionSGid" in vars/vpc-output_vars
      blockinfile:
        path: vars/vpc_output_vars
        backup: yes
        block: |
          BastionSGid: {{BastionSG_out.group_id}}    