---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local 
  gather_facts: False
  tasks:
    - name: Import variable 
      include_vars: vars/vpc_output_vars

    - name: Import instance ami-s
      include_vars: vars/vpro-stack-setup

    - name: create a new EC2 key pair
      amazon.aws.ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: store vprofile key
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: ./loginkey_vpro.pem
        mode: 0600
      when: vprokey_out.changed


